spring.application.name=trabalho-pratico-1-service

server.port=4000

spring.datasource.url=jdbc:postgresql://localhost:5432/trabalho_pratico_1
spring.datasource.username=trabalho1_user
spring.datasource.password=trabalho1_password

spring.jpa.hibernate.ddl-auto=update

# Configurações do Eureka Client - Service Discovery
eureka.client.service-url.defaultZone=http://localhost:8761/eureka

# Indicar para o servidor registrar o IP do serviço e não o nome de domínio  
eureka.instance.prefer-ip-address=true